name: zefyr
description: Clean, minimalistic and collaboration-ready rich text editor for Flutter.
version: 0.5.0
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
homepage: https://github.com/memspace/zefyr

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.14.6
  #url_launcher: ^5.0.0
  #image_picker: ^0.5.0
  url_launcher: ^5.1.0
  image_picker: ^0.6.0+17
  quill_delta: ^1.0.0-dev.1.0
  notus: 
    path: ../notus
  meta: ^1.1.0
  flutter_colorpicker:
    git: https://github.com/twinsunllc/flutter_colorpicker

dev_dependencies:
  flutter_test:
    sdk: flutter